# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8337080bf1cdb3cdd82dfac064b4a424f3f4b69dd0eb9435db7aca6422cf27618916cc21bb3c14a5964b9b0d63cbf2b34dca37979e11d0d6ea085e4fc9a38e31

test:
  secret_key_base: 3ecad18d10bdf5efcd85311144dbbe54e69706cf7921df6f3de941c23bf40395e5df6cb1126f34d974b5a890f9a39d554131b43d4236fd56ac470fa72b38f018

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
